### PR TITLE
create channels table by copying items

### PR DESCRIPTION
**Pull request by scottgrayson**

### CODE REVIEW

**Comment by scottgrayson** [comment]
@ruslantalpa trying to take my first steps with writing migrations. Just copied the code i saw from `items` table and renamed it to `channels`

`test_db` is failing. can't find `channels` view or table not sure if i made a code mistake, or if the migrations aren't being re-run.

could not get the devtools to produce any output either:
image

**Comment by ruslantalpa** [comment]
the image here shows how you installed dev tools, i don't see the output of the test_db
looking at your code it seems fine or at least 95% correct so it must be somethigin small, but again, i don't see here the error.

the devtools have no relation with `integration tests`, they are separate things
devtools are (for now) a way to view the output logs of all the components in one place and also reload containers whenever you change a file (kind of like hot code reload).

with these changes, show me the output of
`docker-compose up` and then for `npm test`

**Comment by scottgrayson** [comment]
thanks for your help @ruslantalpa   
Whenever i change a migration, do i simply run the tests again? Or do i need to run a docker command before testing?  I think running migrations is the step i am missing.

requested output:  
image

**Comment by ruslantalpa** [comment]
On phone now so it will be short.
Do a
Docker-compose down
Then 
Docker-compose up

After this tests will work


In order for the changes to ve detected and loaded in the db, sz needs to be running constantly. Just changing files will not get the changes in the db.

I'll explain in detail tomorrow

**Comment by scottgrayson** [comment]
Success! Thanks! I'll be online to ask about `sz` devtools tomorrow
image

**Comment by ruslantalpa** [comment]
So this is what happened.

Usually when you work with ruby/php/node you are used to saving a file and then running the next request/test and have it use the new code. Here however we are talking about SQL, nginx configs (and lua scripts, but they are more like ruby/php)
Databases and webservers (postgresql/nginx) dont care about your files, you need to execute the sql within a running db instance to have it live. you need to restart the webserver (or send HUP) for the configs to apply.
Of course the php/ruby/... workflow is nice and we want to replicate that when developing locally with PostgREST so this is where the subzero devtools come in.
First you do `docker-compose up -d` which will bring up the db/nginx/postgrest with the current files. After this you need to start the devtools (sz).
It has 2 primary jobs

- Give you a nice interface to view all the output log of every component (db/nginx/postgrest) which are configured for detailed/verbose output.
- What the changes on the filesystem and load the new code into the running servers (sql/configs) so that once you save a file, be that sql/conf/lua the change is immediately live and you can run your next request or reexecute the tests. 

PS: make sure you download v0.0.7 of devtools which i pushed today, i added a small but useful change.

**Pull request closed without merging**
